name: Assignment1

on:
  push:
    branches:
      - Assignment1
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout the repo
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_CREATED_SP }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Run dotnet build and publish
      - name: "Show Connection Success"
        run: |
          az account show

      # Extra Credit: Create a resource
      - name: "Create A Resource"
        run: |
          az staticwebapp create -g EWU-CSCD396-2023-Fall -n a1example

      # List Resources
      - name: "List Resources"
        run: |
          az resource list

      # Extra Credit: Delete the resource
      - name: "Delete The Resource"
        run: |
          az staticwebapp delete -n a1example

      - name: Logout
        run: |
          az logout
